/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BottomNavigation: typeof import('./components/BottomNavigation.vue')['default']
    ConversationArea: typeof import('./components/ConversationArea.vue')['default']
    ConversationView: typeof import('./components/ConversationView.vue')['default']
    DisplayModeToggle: typeof import('./components/DisplayModeToggle.vue')['default']
    LanguageInput: typeof import('./components/LanguageInput.vue')['default']
    MessageBubble: typeof import('./components/MessageBubble.vue')['default']
    MicrophoneButton: typeof import('./components/MicrophoneButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
