/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Anchor: typeof import('./components/Anchor.vue')['default']
    AppBar: typeof import('./components/Layout/AppBar.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Breadcrumbs: typeof import('./components/Layout/Breadcrumbs.vue')['default']
    copy: typeof import('./components/EChartsBarChartRenderer copy.vue')['default']
    DatePicker: typeof import('./components/DatePicker.vue')['default']
    DateTimeInput: typeof import('./components/DateTimeInput.vue')['default']
    Drawer: typeof import('./components/Drawer.vue')['default']
    EChartsBarChartRenderer: typeof import('./components/EChartsBarChartRenderer.vue')['default']
    EChartsBarChartRenderer2: typeof import('./components/EChartsBarChartRenderer2.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    HomeIcon: typeof import('./components/icons/HomeIcon.vue')['default']
    Input: typeof import('./components/Input.vue')['default']
    LanguageSwitcher: typeof import('./components/Layout/LanguageSwitcher.vue')['default']
    Loading: typeof import('./components/Loading.vue')['default']
    Menu: typeof import('./components/Layout/Menu.vue')['default']
    MenuItem: typeof import('./components/Layout/MenuItem.vue')['default']
    Message: typeof import('./components/Message.vue')['default']
    MessageBox: typeof import('./components/MessageBox.vue')['default']
    Notification: typeof import('./components/Notification.vue')['default']
    PivotTableWithLinks: typeof import('./components/PivotTableWithLinks.vue')['default']
    ProSidebarDemo: typeof import('./components/ProSidebarDemo.vue')['default']
    ProSidebarMenuItem: typeof import('./components/ProSidebarMenuItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./components/Layout/Sidebar.vue')['default']
    TableWithLinksRenderer: typeof import('./components/TableWithLinksRenderer.vue')['default']
    TimePicker: typeof import('./components/TimePicker.vue')['default']
    UserInfo: typeof import('./components/Layout/UserInfo.vue')['default']
  }
}
